version: '3'
volumes:
  app-db:
services:
  appweb:
   image: nginx:alpine
   ports:
    - "8080:80"
   expose:
    - "3000"
   volumes:
    - .:/code
    - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
   networks:
    - app-network
   depends_on:
    - appcode
  appcode:
    build:
     context: .
     dockerfile: ./.docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
     - .:/code
     - ./.docker/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
     - ./.docker/php.ini:/usr/local/etc/php/php.ini
    networks:
     - app-network
  appdb:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - app-db:/var/www/html
    networks:
     - app-network

networks:
    app-network:
        driver: bridge
